name: Spark Move Generator Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install build-essential -y
    - name: Build
      run: make
    - name: Run tests
      run: make test

